---
abstract: 'A default constructor for standard objects'
author:
  - 'Alex Kalderimis <alex at gmail dot com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-New
provides:
  Object::New:
    file: lib/Object/New.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
